#!/bin/bash

set -euo pipefail

parent_dir="$(cd "$(dirname "$0")" && pwd)"

dependency_name="$(jq -r .name source/data.json)"
version="$(jq -r .version source/data.json)"

"${parent_dir}/${dependency_name}/run" "${version}"
