#!/usr/bin/env bash

set -euo pipefail

build_args=$(cat "${BUILD_ARGS_FILE}" | awk '{printf " --build-arg \"%s\"", $0}')
build_str="docker build${build_args} --no-cache -t img "${CONTEXT}" ; docker save -o image/image.tar img"
echo ${build_str}
eval ${build_str}