#!/bin/bash

set -euo pipefail

if [[ "${BASE_IMAGE}" != "" ]]; then
  echo "base_image=${BASE_IMAGE}" >> build-args/args
fi

if [[ "${STACK_ID}" != "" ]]; then
  echo "stack_id=${STACK_ID}" >> build-args/args
fi

if [[ -d mixins-label ]]; then
  echo "mixins=$(cat mixins-label/*)" >> build-args/args
else
  echo "mixins=[]" >> build-args/args
fi

if [[ "${STACK}" != "" && "${IMAGE}" != "" && -d stacks ]]; then
  echo "sources=$(cat stacks/arch/x86_64/* | tr '\n' '#' | sed 's/#/\\n/g')" >> build-args/args
  echo "packages=$(cat "stacks/packages/${STACK}/${IMAGE}" | tr '\n' ' ')" >> build-args/args
fi
