#!/bin/bash

set -euo pipefail

if [[ "${BASE_IMAGE}" != "" ]]; then
  echo "base_image=${BASE_IMAGE}" >> build-args/args
fi

if [[ "${STACK_ID}" != "" ]]; then
  echo "stack_id=${STACK_ID}" >> build-args/args
fi

if [[ -d mixins-label ]]; then
  echo "mixins=$(cat mixins-label/*)" >> build-args/args
else
  echo "mixins=[]" >> build-args/args
fi
