#!/bin/bash

set -euo pipefail

start_docker() {
  #shellcheck source=../../scripts/start-docker
  source "./bre-ci/scripts/start-docker"
  util::docker::start
  trap util::docker::stop EXIT
}

pull_images() {
  docker login -u _json_key --password-stdin https://gcr.io/cf-buildpacks-releng < <(echo "${GCP_SERVICE_ACCOUNT_KEY}")

  docker pull "${BUILD_IMAGE}"
  docker pull "${RUN_IMAGE}"
}

create_builder() {
  cat > test-builder.toml << EOF
description = "Test go builder"

[[buildpacks]]
uri = "go-0.0.7.cnb"

[[order]]

[[order.group]]
id = "paketo-buildpacks/go"

[stack]
id = "${STACK_ID}"
build-image = "${BUILD_IMAGE}"
run-image = "${RUN_IMAGE}"
EOF

  pack create-builder test-builder -b test-builder.toml
}

build_and_run_test_app() {
  pack build test-app --builder test-builder --path fixtures/

  docker run test-app
}

main() {
  start_docker
  pull_images

  pushd bre-ci/tasks/test-stack > /dev/null
    create_builder
    build_and_run_test_app
  popd > /dev/null
}

main "$@"
