#!/bin/bash

set -euo pipefail

start_docker() {
  #shellcheck source=../../scripts/start-docker
  source "./bre-ci/scripts/start-docker"
  util::docker::start
  trap util::docker::stop EXIT
}

create_builder() {
  build_image="gcr.io/paketo-buildpacks/build:${TAG}"
  run_image="gcr.io/paketo-buildpacks/run:${TAG}"

  if [[ "${IMAGE_TYPE}" == "build" ]]; then
    build_image="${IMAGE}"
  else
    run_image="${IMAGE}"
  fi

  docker login -u _json_key --password-stdin https://gcr.io/cf-buildpacks-releng < <(echo "${GCP_SERVICE_ACCOUNT_KEY}")

  docker pull "${IMAGE}"

  cat > test-builder.toml << EOF
description = "Test go builder"

[[buildpacks]]
uri = "go-0.0.7.cnb"

[[order]]

[[order.group]]
id = "paketo-buildpacks/go"

[stack]
id = "${STACK_ID}"
build-image = "${build_image}"
run-image = "${run_image}"
EOF

  pack create-builder test-builder -b test-builder.toml
}

build_and_run_test_app() {
  pack build test-app --builder test-builder --path fixtures/

  docker run test-app
}

main() {
  start_docker

  pushd bre-ci/tasks/test-stack > /dev/null
    create_builder
    build_and_run_test_app
  popd > /dev/null
}

main "$@"
