#!/bin/bash

set -euo pipefail

login() {
  fly -t ci login -c "${CONCOURSE_URL}" -n "${CONCOURSE_TEAM}" -u "${CONCOURSE_USERNAME}" -p "${CONCOURSE_PASSWORD}"
}

check_and_pin_resource() {
  version=$1

  fly -t ci check-resource \
    -r "${PIPELINE_NAME}/cnb-lifecycle-release-${version}"

  fly -t ci pin-resource \
    -r "${PIPELINE_NAME}/cnb-lifecycle-release-${version}" \
    -v "tag:$(jq -r ".\"${version}\".lifecycle_ref" lifecycle-metadata-file/*.json)"
}

main() {
  login

  check_and_pin_resource "latest"
  check_and_pin_resource "n-1"
  check_and_pin_resource "n-2"
}

main "$@"
