#!/bin/bash

set -euo pipefail

parent_dir="$(cd "$(dirname "$0")" && pwd)"

check_php_is_provided() {
  if ! ls required_dependency* >/dev/null 2>&1; then
    echo "Must provide at least one PHP version to test against"
    exit 1
  fi
}

extract_tarball_caapm() {
  rm -rf caapm
  mkdir caapm
  tar -xf dependency/*.tar.gz -C caapm
}


extract_tarball_php() {
  required_dependency_dir=$1

  rm -rf php
  mkdir php
  tar -xf "${required_dependency_dir}"/*.tgz -C php
}

check_caapm() {
  configure_php
  install_caapm
}

configure_php() {
  extension_dir="$(find "$PWD/php/lib/php/extensions" -name "no-debug-non-zts-*")"

  sed \
    -i \
    "s|extension_dir=.*|extension_dir='${extension_dir}'|" \
    "php/bin/php-config"

  sed \
    "s|REPLACE_ME_EXTENSION_DIR|${extension_dir}|" \
    "${parent_dir}/fixtures/php.ini.template" \
    > "$PWD/php/etc/php.ini"
}

install_caapm() {
  install_output="$(./caapm/apm-phpagent/installer.sh -phproot "$PWD/php/bin" -ini "$PWD/php/etc" | tee /dev/tty)"
  if ! [[ ${install_output} == *"CA APM PHP Probe Agent is successfully installed on your machine"* ]]; then
    echo "Install failed"
    exit 1
  fi
}

main() {
  check_php_is_provided

  for required_dependency in required_dependency_*; do
    extract_tarball_php "${required_dependency}"
    extract_tarball_caapm
    check_caapm
  done

  echo "All tests passed!"
}

main "$@"
