#!/usr/bin/env bash

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")" && cd .. && pwd)"

filter=
if [ "$#" -eq 1 ]; then
  filter="$1"
fi

target="buildpacks"

fly -t "$target" status >/dev/null 2>&1 || fly -t "$target" login -b

for pipeline_dir in "$REPO_ROOT"/pipelines/*; do
  pipeline_name="$(basename "${pipeline_dir%.yml}")"
  if [[ $filter != "" ]] && [[ ! $pipeline_name =~ $filter ]]; then
    continue
  fi

  echo "Setting $pipeline_name"
  pipeline_config="$(ytt -f "$pipeline_dir")"
  fly -t "$target" set-pipeline -p "$pipeline_name" -c <(echo "$pipeline_config")
done
