#!/usr/bin/env bash

set -euo pipefail

if [ -d "build-image-package-list" ] && [ -d "run-image-package-list" ]; then
  sort -u build-image-package-list/package-list -o build-image-package-list/package-list
  sort -u run-image-package-list/package-list -o run-image-package-list/package-list

  shared_packages="$(comm -12 build-image-package-list/package-list run-image-package-list/package-list)"
  build_only_packages="$(comm -23 build-image-package-list/package-list run-image-package-list/package-list)"
  run_only_packages="$(comm -13 build-image-package-list/package-list run-image-package-list/package-list)"
else
  shared_packages=""
  build_only_packages=""
  run_only_packages=""
fi

additional_build_mixins="$(cat "build-base-dockerfile/${STACK}/cnb/build/additional-mixins")"
additional_run_mixins="$(cat "run-base-dockerfile/${STACK}/cnb/run/additional-mixins")"

build_mixins_label="$(cat <<EOF
${shared_packages}
$([[ -n "${shared_packages}" ]] && echo "${shared_packages}" | sed 's/^/build:/')
$([[ -n "${build_only_packages}" ]] && echo "${build_only_packages}" | sed 's/^/build:/')
$([[ -n "${additional_build_mixins}" ]] && echo "${additional_build_mixins}")
EOF
)"

run_mixins_label="$(cat <<EOF
${shared_packages}
$([[ -n "${shared_packages}" ]] && echo "${shared_packages}" | sed 's/^/run:/')
$([[ -n "${run_only_packages}" ]] && echo "${run_only_packages}" | sed 's/^/run:/')
$([[ -n "${additional_run_mixins}" ]] && echo "${additional_run_mixins}")
EOF
)"

echo "${build_mixins_label}" | jq -cnR '[inputs | select(length>0)]' > build-mixins-label/mixins.json
echo "${run_mixins_label}" | jq -cnR '[inputs | select(length>0)]' > run-mixins-label/mixins.json

echo "Wrote mixins..."
cat build-mixins-label/mixins.json
cat run-mixins-label/mixins.json
