#!/bin/bash

set -euo pipefail

if [[ -d "platform-api-version" ]]; then
  platform_api_version="$(cat platform-api-version/version)"
  echo "platform-api-${platform_api_version} " > tags/tags
fi

if [[ -d "version" ]]; then
  version="$(cat version/version)"
  echo "${version} " >> tags/tags
fi

echo "${TAGS}" >> tags/tags
