#!/usr/bin/env bash

set -euo pipefail

check_if_tag_exists() {
  local tags_list=$1
  local search_tag=$2
  local location=$3
  local image=$4

  for tag in ${tags_list}; do
    if [[ "${search_tag}" == "${tag}" ]] || [[ "${search_tag}" == "${tag}-cnb" ]]; then
      echo "Tag ${search_tag} already exists in ${location} for ${image} image"
      exit 1
    fi
    if [[ "${search_tag}" == *-full-cf ]]; then
      cf_search_tag="${search_tag%full-cf}-full-cnb-cf"
      if [[ "${cf_search_tag}" == "${tag}" ]]; then
        echo "Tag ${cf_search_tag} already exists in ${location} for ${image} image"
        exit 1
      fi
    fi
  done
}

check_gcr_registry() {
  local search_tag=$1
  for image in "build" "run"; do
    tags="$(curl -s "https://gcr.io/v2/paketo-buildpacks/${image}/tags/list" | jq -r ".tags[]")"
    check_if_tag_exists "${tags}" "${search_tag}" "gcr.io/paketo-buildpacks" "${image}"
  done
}

check_dockerhub_registry() {
  local search_tag=$1
  for image in "build" "run"; do
    paketo_tags="$(curl -s "https://registry.hub.docker.com/v2/repositories/paketobuildpacks/${image}/tags?page_size=1000" | jq '.results[].name')"
    check_if_tag_exists "${paketo_tags}" "${search_tag}" "registry.hub.docker.com/paketobuildpacks" "${image}"

    cloudfoundry_tags="$(curl -s "https://registry.hub.docker.com/v2/repositories/cloudfoundry/${image}/tags?page_size=1000" | jq '.results[].name')"
    check_if_tag_exists "${cloudfoundry_tags}" "${search_tag}" "registry.hub.docker.com/cloudfoundry" "${image}"
  done
}

main() {
  search_tag="$(cat version/version)"

  check_gcr_registry "${search_tag}"
  check_dockerhub_registry "${search_tag}"
}

main "$@"
