#!/usr/bin/env bash

set -euo pipefail

check_if_tag_exists() {
  local tags_list=$1
  local search_tag=$2

  for tag in "${tags_list[@]}"; do
    if [[ "${tag}" =~ ${search_tag} ]]; then
      echo "Tag ${search_tag} already exists"
      exit 1
    fi
    if [[ "${search_tag}" == *-full-cf ]]; then
      cf_search_tag="${search_tag%full-cf}-full-cnb-cf"
      if [[ "${tag}" =~ ${cf_search_tag} ]]; then
        echo "Tag ${cf_search_tag} already exists"
        exit 1
      fi
    fi
  done
}

check_gcr_registry() {
  local search_tag=$1
  for image in "build" "run"; do
    tags="$(curl "https://gcr.io/v2/paketo-buildpacks/${image}/tags/list" | jq -r ".tags[]")"
    check_if_tag_exists "${tags}" "${search_tag}"
  done
}

check_dockerhub_registry() {
  local search_tag=$1
  for image in "build" "run"; do
    paketo_tags="$(curl "https://registry.hub.docker.com/v2/repositories/paketobuildpacks/${image}/tags?page_size=1000" | jq '.results[].name')"
    check_if_tag_exists "${paketo_tags}" "${search_tag}"

    cloudfoundry_tags="$(curl "https://registry.hub.docker.com/v2/repositories/cloudfoundry/${image}/tags?page_size=1000" | jq '.results[].name')"
    check_if_tag_exists "${cloudfoundry_tags}" "${search_tag}"
  done
}

main() {
  search_tag="$(cat version/version)"

  check_gcr_registry "${search_tag}"
  check_dockerhub_registry "${search_tag}"
}

main "$@"
